.TH SCOPE-CLI "1" "June 2016" "scope-cli 0.12"
.SH NAME
scope-cli \- a remote procedure call client for Scope Coin. 
.SH SYNOPSIS
scope-cli [options] <command> [params] \- Send command to Scope Coin. 
.TP
scope-cli [options] help \- Asks Scope Coin for a list of supported commands.
.SH DESCRIPTION
This manual page documents the scope-cli program. scope-cli is an RPC client used to send commands to Scope Coin.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBscoped\fP, \fBscope.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
